name: inventi_coding_exam
description: "Inventi Coding Exam"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  equatable: ^2.0.5
  dart_mappable: ^4.2.1
  get_it: ^8.0.0
  shimmer: ^3.0.0
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  test: ^1.25.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.2.3
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  mocktail: ^1.0.4


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/



  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf