// Mocks generated by Mockito 5.4.4 from annotations
// in inventi_coding_exam/test/screens/homepage_screen/data/repositories/homepage_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:inventi_coding_exam/screens/homepage_screen/data/datasources/homepage_remote_datasource.dart'
    as _i4;
import 'package:inventi_coding_exam/screens/homepage_screen/data/model/homepage_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomePageModel_1 extends _i1.SmartFake implements _i3.HomePageModel {
  _FakeHomePageModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomePageRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomePageRemoteDataSourceImpl extends _i1.Mock
    implements _i4.HomePageRemoteDataSourceImpl {
  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i5.Future<_i3.HomePageModel> getRandomString() => (super.noSuchMethod(
        Invocation.method(
          #getRandomString,
          [],
        ),
        returnValue: _i5.Future<_i3.HomePageModel>.value(_FakeHomePageModel_1(
          this,
          Invocation.method(
            #getRandomString,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.HomePageModel>.value(_FakeHomePageModel_1(
          this,
          Invocation.method(
            #getRandomString,
            [],
          ),
        )),
      ) as _i5.Future<_i3.HomePageModel>);
}
